# يستخدم سير العمل هذا إجراءات غير معتمدة من GitHub.
# يتم توفيرها من قبل طرف ثالث ويحكمها
# شروط خدمة منفصلة، سياسة الخصوصية، والدعم
# الوثائق.

# سيقوم سير العمل هذا بتثبيت Deno ثم تشغيل "الوبر الدينو" و "اختبار الدينو".
# لمزيد من المعلومات انظر: https://github.com/denoland/setup-deno

الاسم.: دينو.

على.:
  دفع. :
  الفروع. : ["الرئيسية"]
  سحب_طلب. :
  الفروع. : ["الرئيسية"]

الأذونات.:
  المحتويات.  : قراءة.

وظائف.:
  اختبار. :
  يعمل على.  : أوبونتو-الأحدث.

    خطوات   :
 - الاسم.: إعداد الريبو.
  الاستخدامات.  : الإجراءات/الخروج @v4

 - الاسم.: الإعداد دينو.
        # يستخدم: denoland/setup-deno@v1
  الاستخدامات. : دينولاند/إعداد-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
 مع... :
  دينو-الإصدار. : V1.x

      # إلغاء التعليق على هذه الخطوة للتحقق من استخدام "deno fmt" في كل التزام.
      # - الاسم: التحقق من التنسيق
      # تشغيل: دينو FMT - تحقق

 الاسم: تشغيل اسم البطانة.: تشغيل التمهيدي.
  تشغيل.  : دينو لينت.  : دينو لينت.

 - الاسم: تشغيل الاختبارات name: إجراء الاختبارات.
  تشغيل.  : اختبار دينو -A. : اختبار دينو -A.
